smtp_on: true
smtp_host: smtp.163.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: zeusweb@163.com
smtp_password: SDZeus246810
smtp_from: zeusweb@163.com
smtp_fromname: 宙思科技
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
langcode: zh-hans
